services:
  jd-stock:
    image: zhuweitung/jd-stock:latest
    container_name: jd-stock
    restart: always
    ports:
      - "9090:8080"
    volumes:
      - ./config:/app/config
    environment:
      TZ: Asia/Shanghai
